<?php

register_post_type( 'crb_story', array(
	'labels' => array(
		'name' => __( 'Stories', 'crb' ),
		'singular_name' => __( 'Story', 'crb' ),
		'add_new' => __( 'Add New', 'crb' ),
		'add_new_item' => __( 'Add new Story', 'crb' ),
		'view_item' => __( 'View Story', 'cr   b' ),
		'edit_item' => __( 'Edit Story', 'crb' ),
		'new_item' => __( 'New Story', 'crb' ),
		'view_item' => __( 'View Story', 'crb' ),
		'search_items' => __( 'Search Story', 'crb' ),
		'not_found' =>  __( 'No Story found', 'crb' ),
		'not_found_in_trash' => __( 'No Story found in trash', 'crb' ),
	),
	'public' => true,
	'exclude_from_search' => false,
	'show_ui' => true,
	'capability_type' => 'post',
	'hierarchical' => true,
	'_edit_link' => 'post.php?post=%d',
	'rewrite' => array(
		'slug' => 'story',
		'with_front' => false,
	),
	'query_var' => true,
	'menu_icon' => 'dashicons-admin-page',
	'supports' => array( 'title', 'editor', 'thumbnail', 'page-attributes' ),
) );

register_post_type( 'crb_video', array(
  'labels' => array(
    'name' => __( 'Videos', 'crb' ),
    'singular_name' => __( 'Video', 'crb' ),
    'add_new' => __( 'Add New', 'crb' ),
    'add_new_item' => __( 'Add new Video', 'crb' ),
    'view_item' => __( 'View Video', 'cr   b' ),
    'edit_item' => __( 'Edit Video', 'crb' ),
    'new_item' => __( 'New Video', 'crb' ),
    'view_item' => __( 'View Video', 'crb' ),
    'search_items' => __( 'Search Video', 'crb' ),
    'not_found' =>  __( 'No Video found', 'crb' ),
    'not_found_in_trash' => __( 'No Video found in trash', 'crb' ),
  ),
  'public' => true,
  'exclude_from_search' => false,
  'show_ui' => true,
  'capability_type' => 'post',
  'hierarchical' => true,
  '_edit_link' => 'post.php?post=%d',
  'rewrite' => array(
    'slug' => 'video',
    'with_front' => false,
  ),
  'query_var' => true,
  'menu_icon' => 'dashicons-video-alt2',
  'supports' => array( 'title', 'editor', 'thumbnail', 'excerpt' ),
) );

register_post_type( 'crb_staff', array(
  'labels' => array(
    'name' => __( 'Staff', 'crb' ),
    'singular_name' => __( 'Member', 'crb' ),
    'add_new' => __( 'Add New', 'crb' ),
    'add_new_item' => __( 'Add new Member', 'crb' ),
    'view_item' => __( 'View Member', 'cr   b' ),
    'edit_item' => __( 'Edit Member', 'crb' ),
    'new_item' => __( 'New Member', 'crb' ),
    'view_item' => __( 'View Member', 'crb' ),
    'search_items' => __( 'Search Member', 'crb' ),
    'not_found' =>  __( 'No Member found', 'crb' ),
    'not_found_in_trash' => __( 'No Member found in trash', 'crb' ),
  ),
  'public' => true,
  'exclude_from_search' => false,
  'show_ui' => true,
  'capability_type' => 'post',
  'hierarchical' => true,
  '_edit_link' => 'post.php?post=%d',
  'rewrite' => array(
    'slug' => 'member',
    'with_front' => false,
  ),
  'query_var' => true,
  'menu_icon' => 'dashicons-groups',
  'supports' => array( 'title','editor', 'thumbnail' ),
) );

register_post_type( 'crb_country', array(
  'labels' => array(
    'name' => __( 'Countries', 'crb' ),
    'singular_name' => __( 'Country', 'crb' ),
    'add_new' => __( 'Add New', 'crb' ),
    'add_new_item' => __( 'Add new Country', 'crb' ),
    'view_item' => __( 'View Country', 'cr   b' ),
    'edit_item' => __( 'Edit Country', 'crb' ),
    'new_item' => __( 'New Country', 'crb' ),
    'view_item' => __( 'View Country', 'crb' ),
    'search_items' => __( 'Search Country', 'crb' ),
    'not_found' =>  __( 'No Country found', 'crb' ),
    'not_found_in_trash' => __( 'No Country found in trash', 'crb' ),
  ),
  'public' => true,
  'exclude_from_search' => false,
  'show_ui' => true,
  'capability_type' => 'post',
  'hierarchical' => true,
  '_edit_link' => 'post.php?post=%d',
  'rewrite' => array(
    'slug' => 'country',
    'with_front' => false,
  ),
  'query_var' => true,
  'menu_icon' => 'dashicons-admin-site',
  'supports' => array( 'title', 'thumbnail' ),
) );

register_post_type( 'crb_region', array(
  'labels' => array(
    'name' => __( 'Regions', 'crb' ),
    'singular_name' => __( 'Region', 'crb' ),
    'add_new' => __( 'Add New', 'crb' ),
    'add_new_item' => __( 'Add new Region', 'crb' ),
    'view_item' => __( 'View Region', 'cr   b' ),
    'edit_item' => __( 'Edit Region', 'crb' ),
    'new_item' => __( 'New Region', 'crb' ),
    'view_item' => __( 'View Region', 'crb' ),
    'search_items' => __( 'Search Region', 'crb' ),
    'not_found' =>  __( 'No Region found', 'crb' ),
    'not_found_in_trash' => __( 'No Region found in trash', 'crb' ),
  ),
  'public' => false,
  'exclude_from_search' => true,
  'show_ui' => true,
  'capability_type' => 'post',
  'hierarchical' => true,
  '_edit_link' => 'post.php?post=%d',
  'rewrite' => array(
    'slug' => 'region',
    'with_front' => false,
  ),
  'query_var' => true,
  'menu_icon' => 'dashicons-location-alt',
  'supports' => array( 'title' ),
) );
